version: '3.1'
services:
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    restart: always
    depends_on:
        - mongo
    image: mongo-express
    environment:
        - ME_PORT
        - ME_CONFIG_MONGODB_SERVER
        - ME_CONFIG_BASICAUTH_USERNAME
        - ME_CONFIG_BASICAUTH_PASSWORD
    ports:
        - "${ME_PORT}:8081"

  app:
    container_name: node-app
    restart: always
    build: .
    command: npm run watch
    environment:
      - MONGODB_URI_LOCAL=mongodb://mongo:27017/api
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
        - ./:/usr/src/app 
        - nodemodules:/usr/src/app/node_modules

volumes:
    mongo-data: {}
    nodemodules: {}
    apidata: {}
